# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 18:22
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id_board', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('dataFile', models.FileField(upload_to='boardCSV')),
                ('dataFilteredMN', models.FileField(null=True, upload_to='boardCSV')),
                ('dataFilteredGBR', models.FileField(null=True, upload_to='boardCSV')),
                ('dataFilteredBoruta', models.FileField(null=True, upload_to='boardCSV')),
                ('delimiter', models.CharField(choices=[('COMA', 'Coma (,)'), ('TABULACION', 'Tabulated'), ('PUNTO Y COMA', 'Point and coma (;)'), ('ESPACIO', 'Space'), ('OTRO', 'Other')], default='COMA', max_length=20)),
                ('n_genes_initial', models.IntegerField(default=8)),
                ('n_samples', models.PositiveIntegerField(default=0)),
                ('n_genes', models.PositiveIntegerField(default=0)),
                ('n_types', models.PositiveIntegerField(default=0)),
                ('types', models.CharField(max_length=1000, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('confirmed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='BoardShared',
            fields=[
                ('id_board', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('confirmation', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board_share',
            },
        ),
        migrations.AlterUniqueTogether(
            name='boardshared',
            unique_together=set([('board', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([('owner', 'title')]),
        ),
    ]
